name: Naive Bayes CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest tests/test_naive_bayes.py

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: success()

    steps:
      - name: Deployment to Production (Example)
        # Your deployment steps would go here
        run: |
          echo "Deploying the Naïve Bayes algorithm to production..."
          # Example: You might copy files to a server or deploy to a cloud service.
